import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-950 py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="inline-flex items-center gap-2 text-gray-400 hover:text-white mb-10 transition-colors text-sm">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>

        <div className="bg-gray-900 border border-gray-800 rounded-2xl p-8 md:p-12">
          <h1 className="text-3xl font-extrabold text-white mb-2">Terms of Service</h1>
          <p className="text-gray-500 text-sm mb-10">Last updated: April 2026</p>

          <div className="space-y-8 text-gray-300 leading-relaxed">
            {[
              {
                title: "1. Acceptance of Terms",
                content: "By using FitAI Pro, you agree to these Terms of Service. If you do not agree, please do not use the service. These terms apply to all users including free and paid subscribers."
              },
              {
                title: "2. Service Description",
                content: "FitAI Pro provides AI-powered fitness coaching including workout generation, nutrition planning, progress tracking, and an AI chat coach. Workouts are free forever. Nutrition plans beyond the 7-day trial require a paid subscription."
              },
              {
                title: "3. Free Trial",
                content: "New users receive a 7-day free trial of AI diet plans. After the trial, diet plans require a paid subscription. Workouts, AI coaching chat, and progress tracking remain free forever. There is no automatic billing after the trial."
              },
              {
                title: "4. Subscriptions and Payments",
                content: "Paid subscriptions are billed monthly. All payments are processed by Razorpay. Subscriptions can be cancelled at any time via email. You retain access until the end of your current billing period. No refunds for partial months except as required by law."
              },
              {
                title: "5. Refund Policy",
                content: "We offer a 7-day refund policy for new subscribers. If you are unsatisfied within 7 days of your first payment, contact support@fitaipro.com for a full refund. Refunds are not available for renewals."
              },
              {
                title: "6. Medical Disclaimer",
                content: "FitAI Pro is not a medical service. Content generated by our AI is for informational purposes only and should not replace professional medical advice. Always consult a doctor before starting a new fitness program, especially if you have any medical conditions."
              },
              {
                title: "7. User Responsibilities",
                content: "You are responsible for providing accurate information during onboarding. You agree not to misuse the platform, share your account, or attempt to reverse-engineer any part of the service."
              },
              {
                title: "8. Intellectual Property",
                content: "FitAI Pro and its content are owned by FitAI Pro. AI-generated workout plans and meal plans are licensed to you for personal use only. You may not resell or redistribute them."
              },
              {
                title: "9. Termination",
                content: "We reserve the right to terminate accounts that violate these terms. You may delete your account at any time by contacting support@fitaipro.com."
              },
              {
                title: "10. Contact",
                content: "For terms-related questions: support@fitaipro.com"
              },
            ].map((section) => (
              <div key={section.title}>
                <h2 className="text-white font-bold text-lg mb-3">{section.title}</h2>
                <p className="text-gray-400 text-sm leading-relaxed">{section.content}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}