export interface Exercise {
  id: string;
  name: string;
  muscle: string;
  muscleGroup: string;
  equipment: string;
  type: "home_no_equipment" | "home_with_equipment" | "gym";
  gifUrl: string;
  instructions: string[];
  tips: string;
  caloriesPerMin: number; // for calorie tracking
}

// Reliable CDN - exercisedb.dev (free, stable, built for fitness apps)
const CDN = "https://static.exercisedb.dev/media";

export const EXERCISE_LIBRARY: Exercise[] = [
  // ══════════ HOME — NO EQUIPMENT ══════════
  {
    id: "pushup",
    name: "Push Ups",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0061.gif`,
    instructions: ["Start in plank, hands wider than shoulders", "Lower chest to floor", "Push back up fully", "Keep core tight"],
    tips: "Don't let hips sag. Full range of motion.",
    caloriesPerMin: 7,
  },
  {
    id: "squat_bw",
    name: "Bodyweight Squats",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0043.gif`,
    instructions: ["Feet shoulder-width, toes slightly out", "Push hips back, bend knees", "Lower until thighs parallel", "Drive through heels"],
    tips: "Knees track over toes. Chest up.",
    caloriesPerMin: 8,
  },
  {
    id: "plank",
    name: "Plank Hold",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0048.gif`,
    instructions: ["Forearm plank position", "Body straight head to heels", "Engage core and glutes", "Hold for required time"],
    tips: "Breathe normally. Don't hold breath.",
    caloriesPerMin: 4,
  },
  {
    id: "lunge_bw",
    name: "Reverse Lunges",
    muscle: "Legs",
    muscleGroup: "legs",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0034.gif`,
    instructions: ["Stand tall, hip-width", "Step one foot back, lower knee", "Front knee above ankle", "Push through front heel"],
    tips: "Keep torso upright throughout.",
    caloriesPerMin: 7,
  },
  {
    id: "mountain_climber",
    name: "Mountain Climbers",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0029.gif`,
    instructions: ["High plank", "Drive one knee to chest", "Switch legs quickly", "Keep hips level"],
    tips: "Faster = cardio. Slower = core focus.",
    caloriesPerMin: 10,
  },
  {
    id: "burpee",
    name: "Burpees",
    muscle: "Full Body",
    muscleGroup: "cardio",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0013.gif`,
    instructions: ["Standing position", "Drop hands, jump feet back", "Do a pushup", "Jump feet forward, jump up arms overhead"],
    tips: "Step instead of jump to reduce impact.",
    caloriesPerMin: 12,
  },
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    muscle: "Glutes",
    muscleGroup: "glutes_hamstrings",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0027.gif`,
    instructions: ["Lie on back, knees bent", "Push through heels, lift hips", "Squeeze glutes at top", "Lower with control"],
    tips: "Hold 2 seconds at top.",
    caloriesPerMin: 5,
  },
  {
    id: "jumping_jack",
    name: "Jumping Jacks",
    muscle: "Cardio",
    muscleGroup: "cardio",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0081.gif`,
    instructions: ["Feet together, arms at sides", "Jump feet out, raise arms overhead", "Jump back", "Steady rhythm"],
    tips: "Land softly to protect joints.",
    caloriesPerMin: 9,
  },
  {
    id: "crunches",
    name: "Crunches",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0009.gif`,
    instructions: ["Lie back, knees bent", "Hands lightly behind head", "Curl upper body to knees", "Lower with control"],
    tips: "Use abs, not neck.",
    caloriesPerMin: 5,
  },
  {
    id: "high_knees",
    name: "High Knees",
    muscle: "Cardio",
    muscleGroup: "cardio",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0082.gif`,
    instructions: ["Stand feet hip-width", "Run in place, drive knees high", "Pump arms in rhythm", "Land on balls of feet"],
    tips: "Keep core tight, chest up.",
    caloriesPerMin: 11,
  },
  {
    id: "tricep_dip",
    name: "Chair Tricep Dips",
    muscle: "Triceps",
    muscleGroup: "chest_triceps",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0066.gif`,
    instructions: ["Sit on chair edge, hands beside hips", "Slide forward off edge", "Lower by bending elbows to 90°", "Push back up"],
    tips: "Keep back close to chair.",
    caloriesPerMin: 6,
  },
  {
    id: "superman",
    name: "Superman Hold",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0045.gif`,
    instructions: ["Lie face down, arms extended overhead", "Lift arms, chest and legs off floor", "Hold 2 seconds at top", "Lower with control"],
    tips: "Squeeze glutes and back at top.",
    caloriesPerMin: 4,
  },
  {
    id: "wall_sit",
    name: "Wall Sit",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0050.gif`,
    instructions: ["Back flat against wall", "Slide down until thighs parallel", "Knees above ankles", "Hold required time"],
    tips: "Push back into wall. Knees don't cave.",
    caloriesPerMin: 5,
  },
  {
    id: "leg_raise",
    name: "Leg Raises",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0026.gif`,
    instructions: ["Lie flat on back", "Hands under glutes", "Raise legs to 90 degrees", "Lower slowly without touching floor"],
    tips: "Lower back must stay on ground.",
    caloriesPerMin: 5,
  },
  {
    id: "pike_pushup",
    name: "Pike Push Ups",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0042.gif`,
    instructions: ["Downward dog position", "Hips high, head between arms", "Lower head toward floor", "Push back up"],
    tips: "Great shoulder builder without weights.",
    caloriesPerMin: 7,
  },
  // ══════════ HOME — WITH EQUIPMENT ══════════
  {
    id: "db_bench_press",
    name: "Dumbbell Bench Press",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0176.gif`,
    instructions: ["Lie on bench/floor, dumbbells at chest", "Press up until arms extended", "Lower with control", "Keep shoulder blades back"],
    tips: "Slow on the way down.",
    caloriesPerMin: 6,
  },
  {
    id: "db_row",
    name: "Dumbbell Rows",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0226.gif`,
    instructions: ["Hinge at hips, back flat", "Pull dumbbells to hips", "Squeeze shoulder blades", "Lower controlled"],
    tips: "Lead with elbows not hands.",
    caloriesPerMin: 6,
  },
  {
    id: "db_shoulder_press",
    name: "Shoulder Press",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0096.gif`,
    instructions: ["Dumbbells at shoulder height", "Press overhead", "Fully extend arms", "Lower slowly"],
    tips: "Don't arch lower back.",
    caloriesPerMin: 6,
  },
  {
    id: "goblet_squat",
    name: "Goblet Squats",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0200.gif`,
    instructions: ["Hold dumbbell at chest", "Squat deep, chest up", "Elbows inside knees at bottom", "Drive through heels"],
    tips: "Weight helps you squat deeper.",
    caloriesPerMin: 8,
  },
  {
    id: "db_curl",
    name: "Bicep Curls",
    muscle: "Biceps",
    muscleGroup: "back_biceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0299.gif`,
    instructions: ["Arms at sides, palms forward", "Curl to shoulders", "Squeeze biceps", "Lower slowly"],
    tips: "Keep elbows pinned to sides.",
    caloriesPerMin: 5,
  },
  {
    id: "db_rdl",
    name: "Romanian Deadlifts",
    muscle: "Hamstrings",
    muscleGroup: "glutes_hamstrings",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0059.gif`,
    instructions: ["Dumbbells at thighs", "Hinge at hips, back flat", "Lower until hamstring stretch", "Drive hips forward"],
    tips: "Feel the hamstring stretch.",
    caloriesPerMin: 7,
  },
  {
    id: "db_lateral_raise",
    name: "Lateral Raises",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0190.gif`,
    instructions: ["Dumbbells at sides, slight elbow bend", "Raise arms to shoulder height", "Hold briefly", "Lower with control"],
    tips: "Don't shrug. Lead with elbows.",
    caloriesPerMin: 5,
  },
  {
    id: "db_chest_fly",
    name: "Dumbbell Chest Fly",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0180.gif`,
    instructions: ["Lie on back, dumbbells above chest", "Open arms wide, slight elbow bend", "Feel chest stretch at bottom", "Bring back together in arc"],
    tips: "Think of hugging a tree.",
    caloriesPerMin: 5,
  },
  {
    id: "db_lunge",
    name: "Dumbbell Lunges",
    muscle: "Legs",
    muscleGroup: "legs",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0210.gif`,
    instructions: ["Hold dumbbells at sides", "Step forward one leg", "Lower back knee to floor", "Push through front heel"],
    tips: "Torso stays upright.",
    caloriesPerMin: 8,
  },
  {
    id: "db_tricep_ext",
    name: "Tricep Extension",
    muscle: "Triceps",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0302.gif`,
    instructions: ["Hold dumbbell overhead with both hands", "Lower behind head", "Extend back up", "Keep elbows pointing forward"],
    tips: "Don't flare elbows out.",
    caloriesPerMin: 5,
  },
  // ══════════ GYM ══════════
  {
    id: "barbell_bench",
    name: "Barbell Bench Press",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${CDN}/0025.gif`,
    instructions: ["Grip slightly wider than shoulders", "Lower to mid-chest", "Press up in slight arc", "Lock out at top"],
    tips: "Keep feet flat, natural arch.",
    caloriesPerMin: 7,
  },
  {
    id: "deadlift",
    name: "Deadlift",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${CDN}/0003.gif`,
    instructions: ["Bar over mid-foot", "Hinge, grip bar, flat back", "Drive through floor, bar close to body", "Lock hips and knees at top"],
    tips: "NEVER round your back.",
    caloriesPerMin: 8,
  },
  {
    id: "squat_barbell",
    name: "Barbell Back Squat",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${CDN}/0047.gif`,
    instructions: ["Bar on upper traps", "Feet shoulder-width, toes out", "Break at hips and knees together", "Drive hips up"],
    tips: "Chest tall, brace before each rep.",
    caloriesPerMin: 9,
  },
  {
    id: "overhead_press",
    name: "Overhead Press",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${CDN}/0033.gif`,
    instructions: ["Grip just outside shoulders", "Press overhead to full lockout", "Lower to clavicle", "Brace core throughout"],
    tips: "Squeeze glutes and abs.",
    caloriesPerMin: 6,
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${CDN}/0236.gif`,
    instructions: ["Grip wider than shoulders", "Lean back slightly", "Pull to upper chest", "Slowly return to extension"],
    tips: "Drive elbows down toward hips.",
    caloriesPerMin: 6,
  },
  {
    id: "cable_fly",
    name: "Cable Flyes",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${CDN}/0073.gif`,
    instructions: ["Cables at shoulder height", "Arms wide, slight elbow bend", "Bring hands together", "Open slowly to stretch"],
    tips: "Focus on chest stretch.",
    caloriesPerMin: 5,
  },
  {
    id: "leg_press",
    name: "Leg Press",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "machine",
    type: "gym",
    gifUrl: `${CDN}/0056.gif`,
    instructions: ["Feet hip-width on platform", "Lower platform to chest", "Press back without locking knees", "Control throughout"],
    tips: "Lower back stays on pad.",
    caloriesPerMin: 7,
  },
  {
    id: "tricep_pushdown",
    name: "Tricep Pushdowns",
    muscle: "Triceps",
    muscleGroup: "chest_triceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${CDN}/0065.gif`,
    instructions: ["Cable at face height", "Elbows pinned to sides", "Push down to full extension", "Slowly return"],
    tips: "Keep elbows locked to sides.",
    caloriesPerMin: 5,
  },
  {
    id: "face_pull",
    name: "Face Pulls",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "cable",
    type: "gym",
    gifUrl: `${CDN}/0085.gif`,
    instructions: ["Cable at face height", "Pull rope to face, elbows high", "Externally rotate at end", "Slowly return"],
    tips: "Great for shoulder health.",
    caloriesPerMin: 5,
  },
  {
    id: "cable_row",
    name: "Seated Cable Row",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${CDN}/0238.gif`,
    instructions: ["Sit at cable, feet on platform", "Grip handle", "Pull to lower chest", "Squeeze back, slowly extend"],
    tips: "Don't round back.",
    caloriesPerMin: 6,
  },
  {
    id: "incline_db_press",
    name: "Incline DB Press",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "gym",
    gifUrl: `${CDN}/0177.gif`,
    instructions: ["Bench at 30-45 degrees", "Dumbbells at chest level", "Press up and together", "Lower to stretch"],
    tips: "Targets upper chest.",
    caloriesPerMin: 6,
  },
  {
    id: "leg_curl",
    name: "Leg Curl Machine",
    muscle: "Hamstrings",
    muscleGroup: "glutes_hamstrings",
    equipment: "machine",
    type: "gym",
    gifUrl: `${CDN}/0057.gif`,
    instructions: ["Lie face down on machine", "Pad just above heels", "Curl legs toward glutes", "Lower slowly"],
    tips: "Don't arch lower back.",
    caloriesPerMin: 5,
  },
];

// Helpers
export function getExercisesByType(type: string): Exercise[] {
  return EXERCISE_LIBRARY.filter((e) => e.type === type);
}

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_LIBRARY.find((e) => e.id === id);
}

export const muscleEmoji: Record<string, string> = {
  chest: "💪", back: "🔙", shoulders: "🏋️", biceps: "💪",
  triceps: "💪", quads: "🦵", legs: "🦵", glutes: "🍑",
  hamstrings: "🦵", abs: "⚡", cardio: "❤️", "full body": "🔥",
};

export const DAILY_REPEAT_GROUPS = ["core", "cardio"];