export interface Exercise {
  id: string;
  name: string;
  muscle: string;
  muscleGroup: string;
  equipment: string;
  type: "home_no_equipment" | "home_with_equipment" | "gym";
  gifUrl: string;
  instructions: string[];
  tips: string;
  caloriesPerMin: number;
}

// GitHub raw CDN — no hotlink blocking, always works
const G = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";

export const EXERCISE_LIBRARY: Exercise[] = [
  // ══ HOME — NO EQUIPMENT ══════════════════════════════════════════
  {
    id: "pushup",
    name: "Push Ups",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Push-Up/images/0.jpg`,
    instructions: [
      "Start in a high plank — hands slightly wider than shoulders",
      "Lower your chest toward the floor, elbows at 45°",
      "Push back up to full arm extension",
      "Keep core tight throughout",
    ],
    tips: "Don't let hips sag. Full range every rep.",
    caloriesPerMin: 7,
  },
  {
    id: "squat_bw",
    name: "Bodyweight Squats",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Bodyweight-Squat/images/0.jpg`,
    instructions: [
      "Feet shoulder-width apart, toes slightly out",
      "Push hips back and bend knees",
      "Lower until thighs are parallel to floor",
      "Drive through heels to stand",
    ],
    tips: "Keep chest tall. Knees track over toes.",
    caloriesPerMin: 8,
  },
  {
    id: "plank",
    name: "Plank Hold",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Plank/images/0.jpg`,
    instructions: [
      "Forearm plank — elbows under shoulders",
      "Body in straight line head to heels",
      "Engage core, glutes and quads",
      "Hold for required time",
    ],
    tips: "Breathe normally. Don't hold your breath.",
    caloriesPerMin: 4,
  },
  {
    id: "lunge_bw",
    name: "Reverse Lunges",
    muscle: "Legs",
    muscleGroup: "legs",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Lunge/images/0.jpg`,
    instructions: [
      "Stand tall, feet hip-width apart",
      "Step one foot back, lower back knee to floor",
      "Front knee stays above ankle",
      "Push through front heel to return",
    ],
    tips: "Keep torso upright. Control the descent.",
    caloriesPerMin: 7,
  },
  {
    id: "mountain_climber",
    name: "Mountain Climbers",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Mountain-Climber/images/0.jpg`,
    instructions: [
      "Start in a high plank position",
      "Drive one knee toward your chest",
      "Quickly switch legs in a running motion",
      "Keep hips level throughout",
    ],
    tips: "Faster = more cardio. Slower = more core activation.",
    caloriesPerMin: 10,
  },
  {
    id: "burpee",
    name: "Burpees",
    muscle: "Full Body",
    muscleGroup: "cardio",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Burpee/images/0.jpg`,
    instructions: [
      "From standing, drop hands to floor",
      "Jump feet back into a plank",
      "Do one push-up",
      "Jump feet forward then explode up — arms overhead",
    ],
    tips: "Step instead of jump to reduce joint impact.",
    caloriesPerMin: 12,
  },
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    muscle: "Glutes",
    muscleGroup: "glutes_hamstrings",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Glute-Bridge/images/0.jpg`,
    instructions: [
      "Lie on back, knees bent, feet flat",
      "Push through heels to lift hips",
      "Squeeze glutes hard at the top",
      "Lower with control",
    ],
    tips: "Hold 2 seconds at top for maximum glute activation.",
    caloriesPerMin: 5,
  },
  {
    id: "jumping_jack",
    name: "Jumping Jacks",
    muscle: "Cardio",
    muscleGroup: "cardio",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Jumping-Jacks/images/0.jpg`,
    instructions: [
      "Stand with feet together, arms at sides",
      "Jump feet out while raising arms overhead",
      "Jump back to start position",
      "Maintain a steady rhythm",
    ],
    tips: "Land softly to protect your joints.",
    caloriesPerMin: 9,
  },
  {
    id: "crunches",
    name: "Crunches",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Crunch/images/0.jpg`,
    instructions: [
      "Lie on back, knees bent, feet flat",
      "Hands lightly behind your head",
      "Curl upper body toward knees",
      "Lower with control — don't drop",
    ],
    tips: "Use abs not neck. Don't pull your head forward.",
    caloriesPerMin: 5,
  },
  {
    id: "high_knees",
    name: "High Knees",
    muscle: "Cardio",
    muscleGroup: "cardio",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/High-Knee-Run-in-Place/images/0.jpg`,
    instructions: [
      "Stand with feet hip-width apart",
      "Run in place driving knees to hip height",
      "Pump arms in rhythm with legs",
      "Land on balls of feet",
    ],
    tips: "Keep core tight and chest up.",
    caloriesPerMin: 11,
  },
  {
    id: "tricep_dip",
    name: "Chair Tricep Dips",
    muscle: "Triceps",
    muscleGroup: "chest_triceps",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Triceps-Dip/images/0.jpg`,
    instructions: [
      "Sit on chair edge, hands beside hips",
      "Slide forward off edge",
      "Lower by bending elbows to 90°",
      "Push back up to full extension",
    ],
    tips: "Keep back close to the chair throughout.",
    caloriesPerMin: 6,
  },
  {
    id: "superman",
    name: "Superman Hold",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Superman/images/0.jpg`,
    instructions: [
      "Lie face down, arms extended overhead",
      "Simultaneously lift arms, chest and legs",
      "Hold 2 seconds at top",
      "Lower with control",
    ],
    tips: "Squeeze glutes and back muscles at top.",
    caloriesPerMin: 4,
  },
  {
    id: "wall_sit",
    name: "Wall Sit",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Wall-Sit/images/0.jpg`,
    instructions: [
      "Back flat against a wall",
      "Slide down until thighs parallel to floor",
      "Knees directly above ankles",
      "Hold for required time",
    ],
    tips: "Push back firmly into wall. Knees don't cave in.",
    caloriesPerMin: 5,
  },
  {
    id: "leg_raise",
    name: "Leg Raises",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Leg-Raise/images/0.jpg`,
    instructions: [
      "Lie flat on back, hands under glutes",
      "Raise both legs to 90° with control",
      "Slowly lower without touching floor",
      "Repeat",
    ],
    tips: "Lower back must stay pressed into the floor.",
    caloriesPerMin: 5,
  },
  {
    id: "pike_pushup",
    name: "Pike Push Ups",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${G}/Pike-Push-Up/images/0.jpg`,
    instructions: [
      "Start in downward-dog — hips high",
      "Head between arms, looking at feet",
      "Lower head toward floor by bending elbows",
      "Push back up",
    ],
    tips: "Great shoulder builder with zero equipment.",
    caloriesPerMin: 7,
  },

  // ══ HOME — WITH EQUIPMENT ══════════════════════════════════════════
  {
    id: "db_bench_press",
    name: "Dumbbell Bench Press",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${G}/Dumbbell-Bench-Press/images/0.jpg`,
    instructions: [
      "Lie on bench or floor, dumbbells at chest",
      "Press straight up until arms extended",
      "Lower with control to chest",
      "Keep shoulder blades retracted",
    ],
    tips: "Slow on the way down for better chest activation.",
    caloriesPerMin: 6,
  },
  {
    id: "db_row",
    name: "Dumbbell Rows",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${G}/Bent-Over-Dumbbell-Row/images/0.jpg`,
    instructions: [
      "Hinge at hips, back flat, dumbbells hanging",
      "Pull dumbbells to your hips",
      "Squeeze shoulder blades at top",
      "Lower with control",
    ],
    tips: "Lead with elbows not hands.",
    caloriesPerMin: 6,
  },
  {
    id: "db_shoulder_press",
    name: "Shoulder Press",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${G}/Dumbbell-Shoulder-Press/images/0.jpg`,
    instructions: [
      "Dumbbells at shoulder height, palms forward",
      "Press overhead to full extension",
      "Lower slowly back to start",
      "Keep core braced",
    ],
    tips: "Don't arch lower back. Brace core.",
    caloriesPerMin: 6,
  },
  {
    id: "goblet_squat",
    name: "Goblet Squats",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${G}/Goblet-Squat/images/0.jpg`,
    instructions: [
      "Hold one dumbbell at chest with both hands",
      "Squat deep keeping chest up",
      "Elbows inside knees at bottom",
      "Drive through heels to stand",
    ],
    tips: "Dumbbell helps you squat deeper naturally.",
    caloriesPerMin: 8,
  },
  {
    id: "db_curl",
    name: "Bicep Curls",
    muscle: "Biceps",
    muscleGroup: "back_biceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${G}/Dumbbell-Bicep-Curl/images/0.jpg`,
    instructions: [
      "Stand, dumbbells at sides, palms forward",
      "Curl to shoulder level",
      "Squeeze biceps hard at top",
      "Lower slowly",
    ],
    tips: "Keep elbows pinned to sides throughout.",
    caloriesPerMin: 5,
  },
  {
    id: "db_rdl",
    name: "Romanian Deadlifts",
    muscle: "Hamstrings",
    muscleGroup: "glutes_hamstrings",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${G}/Romanian-Deadlift/images/0.jpg`,
    instructions: [
      "Hold dumbbells in front of thighs",
      "Hinge at hips pushing them back, back flat",
      "Lower until you feel hamstring stretch",
      "Drive hips forward to return",
    ],
    tips: "Feel the stretch in hamstrings. Keep back flat.",
    caloriesPerMin: 7,
  },
  {
    id: "db_lateral_raise",
    name: "Lateral Raises",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${G}/Lateral-Raise/images/0.jpg`,
    instructions: [
      "Dumbbells at sides, slight elbow bend",
      "Raise arms out to shoulder height",
      "Brief pause at top",
      "Lower with control",
    ],
    tips: "Don't shrug. Lead with elbows.",
    caloriesPerMin: 5,
  },
  {
    id: "db_chest_fly",
    name: "Dumbbell Chest Fly",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${G}/Dumbbell-Flyes/images/0.jpg`,
    instructions: [
      "Lie on back, dumbbells above chest, slight elbow bend",
      "Open arms wide in arc",
      "Feel stretch across chest at bottom",
      "Bring back together in same arc",
    ],
    tips: "Think of hugging a large tree.",
    caloriesPerMin: 5,
  },
  {
    id: "db_lunge",
    name: "Dumbbell Lunges",
    muscle: "Legs",
    muscleGroup: "legs",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${G}/Dumbbell-Lunge/images/0.jpg`,
    instructions: [
      "Hold dumbbells at sides, standing tall",
      "Step forward with one leg",
      "Lower back knee toward floor",
      "Push through front heel to return",
    ],
    tips: "Keep torso upright throughout.",
    caloriesPerMin: 8,
  },
  {
    id: "db_tricep_ext",
    name: "Tricep Extension",
    muscle: "Triceps",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${G}/Triceps-Extension/images/0.jpg`,
    instructions: [
      "Hold one dumbbell overhead with both hands",
      "Lower behind head by bending elbows",
      "Extend back to start",
      "Keep elbows pointing forward",
    ],
    tips: "Don't flare your elbows out wide.",
    caloriesPerMin: 5,
  },

  // ══ GYM ══════════════════════════════════════════════════════════
  {
    id: "barbell_bench",
    name: "Barbell Bench Press",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${G}/Barbell-Bench-Press/images/0.jpg`,
    instructions: [
      "Grip bar slightly wider than shoulder-width",
      "Lower to mid-chest with control",
      "Press up in slight arc to start",
      "Lock out at top",
    ],
    tips: "Feet flat on floor. Natural arch in lower back.",
    caloriesPerMin: 7,
  },
  {
    id: "deadlift",
    name: "Deadlift",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${G}/Barbell-Deadlift/images/0.jpg`,
    instructions: [
      "Bar over mid-foot, hip-width stance",
      "Hinge, grip bar, flat back — chest up",
      "Drive through floor, bar stays close to body",
      "Lock out hips and knees at top",
    ],
    tips: "NEVER round your lower back.",
    caloriesPerMin: 8,
  },
  {
    id: "squat_barbell",
    name: "Barbell Back Squat",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${G}/Barbell-Back-Squat/images/0.jpg`,
    instructions: [
      "Bar on upper traps, feet shoulder-width",
      "Toes out 30°",
      "Break at hips and knees simultaneously",
      "Drive hips up through movement",
    ],
    tips: "Chest tall. Brace core before every rep.",
    caloriesPerMin: 9,
  },
  {
    id: "overhead_press",
    name: "Overhead Press",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${G}/Barbell-Overhead-Press/images/0.jpg`,
    instructions: [
      "Grip just outside shoulder-width",
      "Press to full lockout overhead",
      "Bar travels in slight arc around face",
      "Lower to clavicle level",
    ],
    tips: "Squeeze glutes and abs. No lower back arch.",
    caloriesPerMin: 6,
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${G}/Lat-Pulldown/images/0.jpg`,
    instructions: [
      "Wide grip on bar, lean back slightly",
      "Pull bar to upper chest driving elbows down",
      "Slowly return to full extension",
      "Keep chest up throughout",
    ],
    tips: "Think of driving elbows down and back.",
    caloriesPerMin: 6,
  },
  {
    id: "cable_fly",
    name: "Cable Flyes",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${G}/Cable-Crossover/images/0.jpg`,
    instructions: [
      "Set cables at shoulder height",
      "Step forward, arms wide with elbow bend",
      "Bring handles together in wide arc",
      "Open slowly to feel chest stretch",
    ],
    tips: "Focus on the stretch at open position.",
    caloriesPerMin: 5,
  },
  {
    id: "leg_press",
    name: "Leg Press",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "machine",
    type: "gym",
    gifUrl: `${G}/Leg-Press/images/0.jpg`,
    instructions: [
      "Feet hip-width on platform",
      "Release safety and lower platform",
      "Press back without fully locking knees",
      "Control throughout",
    ],
    tips: "Lower back must stay flat against pad.",
    caloriesPerMin: 7,
  },
  {
    id: "tricep_pushdown",
    name: "Tricep Pushdowns",
    muscle: "Triceps",
    muscleGroup: "chest_triceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${G}/Triceps-Pushdown/images/0.jpg`,
    instructions: [
      "Cable at face height, use rope or bar",
      "Elbows pinned to sides",
      "Push down to full extension",
      "Slowly return",
    ],
    tips: "Keep elbows locked to sides. Only forearms move.",
    caloriesPerMin: 5,
  },
  {
    id: "face_pull",
    name: "Face Pulls",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "cable",
    type: "gym",
    gifUrl: `${G}/Face-Pull/images/0.jpg`,
    instructions: [
      "Cable at face height with rope",
      "Pull rope to face, elbows flared high",
      "Externally rotate wrists at end",
      "Slowly return",
    ],
    tips: "Essential for shoulder health. Don't skip.",
    caloriesPerMin: 5,
  },
  {
    id: "cable_row",
    name: "Seated Cable Row",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${G}/Seated-Cable-Row/images/0.jpg`,
    instructions: [
      "Sit at cable machine, feet on platform",
      "Grip handle with both hands",
      "Pull to lower chest squeezing shoulder blades",
      "Slowly extend back to full reach",
    ],
    tips: "Don't round back at stretch position.",
    caloriesPerMin: 6,
  },
  {
    id: "incline_db_press",
    name: "Incline DB Press",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "gym",
    gifUrl: `${G}/Incline-Dumbbell-Press/images/0.jpg`,
    instructions: [
      "Set bench to 30-45°",
      "Dumbbells at chest, press upward",
      "Lower to feel stretch",
      "Repeat",
    ],
    tips: "Targets upper chest. 30° is ideal angle.",
    caloriesPerMin: 6,
  },
  {
    id: "leg_curl",
    name: "Leg Curl Machine",
    muscle: "Hamstrings",
    muscleGroup: "glutes_hamstrings",
    equipment: "machine",
    type: "gym",
    gifUrl: `${G}/Lying-Leg-Curl/images/0.jpg`,
    instructions: [
      "Lie face down, pad just above heels",
      "Curl legs toward glutes",
      "Hold briefly at top",
      "Lower slowly",
    ],
    tips: "Don't arch lower back. Focus on hamstring squeeze.",
    caloriesPerMin: 5,
  },
];

export function getExercisesByType(type: string): Exercise[] {
  return EXERCISE_LIBRARY.filter((e) => e.type === type);
}

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_LIBRARY.find((e) => e.id === id);
}

export const muscleEmoji: Record<string, string> = {
  chest: "💪", back: "🔙", shoulders: "🏋️", biceps: "💪",
  triceps: "💪", quads: "🦵", legs: "🦵", glutes: "🍑",
  hamstrings: "🦵", abs: "⚡", cardio: "❤️", "full body": "🔥",
};

export const DAILY_REPEAT_GROUPS = ["core", "cardio"];