export interface Exercise {
  id: string;
  name: string;
  muscle: string;
  muscleGroup: string;
  equipment: string;
  type: "home_no_equipment" | "home_with_equipment" | "gym";
  gifUrl: string;       // ExerciseDB CDN (browser fallback)
  instructions: string[];
  tips: string;
  caloriesPerMin: number;
}

// ExerciseDB CDN (works in browser, 403 from server — normal)
//const CDN = "https://v2.exercisedb.io/image";
const CDN = "/gifs";

export const EXERCISE_LIBRARY: Exercise[] = [
  // ══════════ HOME — NO EQUIPMENT ══════════════════════════════════════════
  {
    id: "pushup",
    name: "Push Ups",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0061.gif`,
    instructions: [
      "Start in a high plank — hands slightly wider than shoulders",
      "Lower your chest to the floor, elbows at 45°",
      "Push back up to full arm extension",
      "Keep your core tight throughout",
    ],
    tips: "Don't let hips sag. Full range of motion every rep.",
    caloriesPerMin: 7,
  },
  {
    id: "squat_bw",
    name: "Bodyweight Squats",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0043.gif`,
    instructions: [
      "Feet shoulder-width apart, toes slightly out",
      "Push hips back and bend knees together",
      "Lower until thighs are parallel to the floor",
      "Drive through heels to stand",
    ],
    tips: "Keep chest tall. Knees track over toes.",
    caloriesPerMin: 8,
  },
  {
    id: "plank",
    name: "Plank Hold",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0048.gif`,
    instructions: [
      "Forearm plank — elbows under shoulders",
      "Body in a straight line from head to heels",
      "Engage core, glutes, and quads",
      "Hold for the required time",
    ],
    tips: "Breathe normally. Don't hold your breath.",
    caloriesPerMin: 4,
  },
  {
    id: "lunge_bw",
    name: "Reverse Lunges",
    muscle: "Legs",
    muscleGroup: "legs",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0034.gif`,
    instructions: [
      "Stand tall, feet hip-width apart",
      "Step one foot back, lower back knee toward floor",
      "Front knee stays directly above ankle",
      "Push through the front heel to return",
    ],
    tips: "Keep torso upright. Control the descent.",
    caloriesPerMin: 7,
  },
  {
    id: "mountain_climber",
    name: "Mountain Climbers",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0029.gif`,
    instructions: [
      "Start in a high plank position",
      "Drive one knee toward your chest",
      "Quickly switch legs in a running motion",
      "Keep hips level — don't bounce",
    ],
    tips: "Faster = more cardio. Slower = more core activation.",
    caloriesPerMin: 10,
  },
  {
    id: "burpee",
    name: "Burpees",
    muscle: "Full Body",
    muscleGroup: "cardio",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0013.gif`,
    instructions: [
      "From standing, drop hands to the floor",
      "Jump feet back into a plank",
      "Do one push-up",
      "Jump feet forward then explode up — arms overhead",
    ],
    tips: "Step instead of jump to reduce impact on joints.",
    caloriesPerMin: 12,
  },
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    muscle: "Glutes",
    muscleGroup: "glutes_hamstrings",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0027.gif`,
    instructions: [
      "Lie on your back, knees bent, feet flat",
      "Push through heels to lift hips off the floor",
      "Squeeze glutes hard at the top",
      "Lower with control",
    ],
    tips: "Hold 2 seconds at the top for maximum glute activation.",
    caloriesPerMin: 5,
  },
  {
    id: "jumping_jack",
    name: "Jumping Jacks",
    muscle: "Cardio",
    muscleGroup: "cardio",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0081.gif`,
    instructions: [
      "Stand with feet together, arms at sides",
      "Jump feet out while raising arms overhead",
      "Jump back to start position",
      "Maintain a steady rhythm",
    ],
    tips: "Land softly to protect your joints.",
    caloriesPerMin: 9,
  },
  {
    id: "crunches",
    name: "Crunches",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0009.gif`,
    instructions: [
      "Lie on back, knees bent, feet flat",
      "Hands lightly behind your head",
      "Curl your upper body toward your knees",
      "Lower with control — don't drop",
    ],
    tips: "Use abs, not neck. Don't pull your head forward.",
    caloriesPerMin: 5,
  },
  {
    id: "high_knees",
    name: "High Knees",
    muscle: "Cardio",
    muscleGroup: "cardio",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0082.gif`,
    instructions: [
      "Stand with feet hip-width apart",
      "Run in place driving knees to hip height",
      "Pump arms in rhythm with your legs",
      "Land on balls of feet",
    ],
    tips: "Keep core tight and chest up.",
    caloriesPerMin: 11,
  },
  {
    id: "tricep_dip",
    name: "Chair Tricep Dips",
    muscle: "Triceps",
    muscleGroup: "chest_triceps",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0066.gif`,
    instructions: [
      "Sit on the edge of a chair, hands beside hips",
      "Slide forward off the edge",
      "Lower by bending elbows to 90°",
      "Push back up to full extension",
    ],
    tips: "Keep back close to the chair throughout.",
    caloriesPerMin: 6,
  },
  {
    id: "superman",
    name: "Superman Hold",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0045.gif`,
    instructions: [
      "Lie face down, arms extended overhead",
      "Simultaneously lift arms, chest, and legs off the floor",
      "Hold for 2 seconds at the top",
      "Lower with control",
    ],
    tips: "Squeeze your glutes and back muscles at the top.",
    caloriesPerMin: 4,
  },
  {
    id: "wall_sit",
    name: "Wall Sit",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0050.gif`,
    instructions: [
      "Back flat against a wall",
      "Slide down until thighs are parallel to the floor",
      "Knees directly above ankles",
      "Hold for the required time",
    ],
    tips: "Push your back firmly into the wall. Knees shouldn't cave in.",
    caloriesPerMin: 5,
  },
  {
    id: "leg_raise",
    name: "Leg Raises",
    muscle: "Abs",
    muscleGroup: "core",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0026.gif`,
    instructions: [
      "Lie flat on your back, hands under your glutes",
      "Raise both legs to 90° with control",
      "Slowly lower them without touching the floor",
      "Repeat",
    ],
    tips: "Lower back must stay pressed into the floor.",
    caloriesPerMin: 5,
  },
  {
    id: "pike_pushup",
    name: "Pike Push Ups",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "bodyweight",
    type: "home_no_equipment",
    gifUrl: `${CDN}/0042.gif`,
    instructions: [
      "Start in a downward-dog position — hips high",
      "Head between arms, looking at feet",
      "Lower your head toward the floor by bending elbows",
      "Push back up",
    ],
    tips: "Great shoulder builder with zero equipment.",
    caloriesPerMin: 7,
  },

  // ══════════ HOME — WITH EQUIPMENT ════════════════════════════════════════
  {
    id: "db_bench_press",
    name: "Dumbbell Bench Press",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0176.gif`,
    instructions: [
      "Lie on bench or floor, dumbbells at chest level",
      "Press straight up until arms are extended",
      "Lower with control to chest level",
      "Keep shoulder blades retracted throughout",
    ],
    tips: "Slow on the way down for better chest activation.",
    caloriesPerMin: 6,
  },
  {
    id: "db_row",
    name: "Dumbbell Rows",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0226.gif`,
    instructions: [
      "Hinge at hips, back flat, dumbbells hanging",
      "Pull dumbbells to your hips",
      "Squeeze shoulder blades at the top",
      "Lower with control",
    ],
    tips: "Lead with your elbows, not your hands.",
    caloriesPerMin: 6,
  },
  {
    id: "db_shoulder_press",
    name: "Shoulder Press",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0096.gif`,
    instructions: [
      "Dumbbells at shoulder height, palms forward",
      "Press overhead to full arm extension",
      "Lower slowly back to start",
      "Keep core braced throughout",
    ],
    tips: "Don't arch your lower back. Brace your core.",
    caloriesPerMin: 6,
  },
  {
    id: "goblet_squat",
    name: "Goblet Squats",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0200.gif`,
    instructions: [
      "Hold one dumbbell at your chest with both hands",
      "Squat deep, keeping chest up",
      "Elbows should stay inside your knees at the bottom",
      "Drive through heels to stand",
    ],
    tips: "The dumbbell helps you squat deeper naturally.",
    caloriesPerMin: 8,
  },
  {
    id: "db_curl",
    name: "Bicep Curls",
    muscle: "Biceps",
    muscleGroup: "back_biceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0299.gif`,
    instructions: [
      "Stand, dumbbells at your sides, palms forward",
      "Curl to shoulder level",
      "Squeeze biceps hard at the top",
      "Lower slowly",
    ],
    tips: "Keep elbows pinned to your sides throughout.",
    caloriesPerMin: 5,
  },
  {
    id: "db_rdl",
    name: "Romanian Deadlifts",
    muscle: "Hamstrings",
    muscleGroup: "glutes_hamstrings",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0059.gif`,
    instructions: [
      "Hold dumbbells in front of thighs",
      "Hinge at hips, pushing them back, back flat",
      "Lower until you feel a hamstring stretch",
      "Drive hips forward to return",
    ],
    tips: "Feel the stretch in the hamstrings. Keep the back flat always.",
    caloriesPerMin: 7,
  },
  {
    id: "db_lateral_raise",
    name: "Lateral Raises",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0190.gif`,
    instructions: [
      "Dumbbells at sides, slight bend in elbows",
      "Raise arms out to shoulder height",
      "Brief pause at the top",
      "Lower with control",
    ],
    tips: "Don't shrug. Lead with your elbows, not your wrists.",
    caloriesPerMin: 5,
  },
  {
    id: "db_chest_fly",
    name: "Dumbbell Chest Fly",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0180.gif`,
    instructions: [
      "Lie on back, dumbbells above chest, slight elbow bend",
      "Open arms wide in a wide arc",
      "Feel the stretch across your chest at the bottom",
      "Bring back together in the same arc",
    ],
    tips: "Think of hugging a large tree. Don't straighten arms fully.",
    caloriesPerMin: 5,
  },
  {
    id: "db_lunge",
    name: "Dumbbell Lunges",
    muscle: "Legs",
    muscleGroup: "legs",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0210.gif`,
    instructions: [
      "Hold dumbbells at sides, standing tall",
      "Step forward with one leg",
      "Lower back knee toward the floor",
      "Push through front heel to return",
    ],
    tips: "Keep your torso upright throughout the movement.",
    caloriesPerMin: 8,
  },
  {
    id: "db_tricep_ext",
    name: "Tricep Extension",
    muscle: "Triceps",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "home_with_equipment",
    gifUrl: `${CDN}/0302.gif`,
    instructions: [
      "Hold one dumbbell overhead with both hands",
      "Lower it behind your head by bending elbows",
      "Extend back to start",
      "Keep elbows pointing forward",
    ],
    tips: "Don't flare your elbows out wide.",
    caloriesPerMin: 5,
  },

  // ══════════ GYM ══════════════════════════════════════════════════════════
  {
    id: "barbell_bench",
    name: "Barbell Bench Press",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${CDN}/0025.gif`,
    instructions: [
      "Grip bar slightly wider than shoulder-width",
      "Lower bar to mid-chest with control",
      "Press up in a slight arc back to start",
      "Lock out at the top",
    ],
    tips: "Feet flat on the floor. Natural arch in lower back.",
    caloriesPerMin: 7,
  },
  {
    id: "deadlift",
    name: "Deadlift",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${CDN}/0003.gif`,
    instructions: [
      "Bar over mid-foot, hip-width stance",
      "Hinge, grip the bar, flat back — chest up",
      "Drive through the floor, bar stays close to body",
      "Lock out hips and knees at the top",
    ],
    tips: "NEVER round your lower back. Most important rule.",
    caloriesPerMin: 8,
  },
  {
    id: "squat_barbell",
    name: "Barbell Back Squat",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${CDN}/0047.gif`,
    instructions: [
      "Bar on upper traps (high bar) or rear delts (low bar)",
      "Feet shoulder-width, toes out 30°",
      "Break at hips and knees simultaneously",
      "Drive hips up through the movement",
    ],
    tips: "Chest tall. Brace your core before every rep.",
    caloriesPerMin: 9,
  },
  {
    id: "overhead_press",
    name: "Overhead Press",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "barbell",
    type: "gym",
    gifUrl: `${CDN}/0033.gif`,
    instructions: [
      "Grip just outside shoulder-width",
      "Press to full lockout overhead",
      "Bar travels in a slight arc around your face",
      "Lower to clavicle level",
    ],
    tips: "Squeeze glutes and abs throughout. No lower back arch.",
    caloriesPerMin: 6,
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${CDN}/0236.gif`,
    instructions: [
      "Wide grip on the bar, slightly wider than shoulders",
      "Lean back slightly, chest up",
      "Pull bar to upper chest, driving elbows toward hips",
      "Slowly return to full arm extension",
    ],
    tips: "Think of driving your elbows down and back.",
    caloriesPerMin: 6,
  },
  {
    id: "cable_fly",
    name: "Cable Flyes",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${CDN}/0073.gif`,
    instructions: [
      "Set cables at shoulder height",
      "Step forward, arms wide with slight elbow bend",
      "Bring handles together in a wide arc",
      "Open slowly to feel the chest stretch",
    ],
    tips: "Focus on the stretch at the open position.",
    caloriesPerMin: 5,
  },
  {
    id: "leg_press",
    name: "Leg Press",
    muscle: "Quads",
    muscleGroup: "legs",
    equipment: "machine",
    type: "gym",
    gifUrl: `${CDN}/0056.gif`,
    instructions: [
      "Feet hip-width on the platform",
      "Release safety and lower platform toward chest",
      "Press back without fully locking knees",
      "Control the movement throughout",
    ],
    tips: "Lower back must stay flat against the pad.",
    caloriesPerMin: 7,
  },
  {
    id: "tricep_pushdown",
    name: "Tricep Pushdowns",
    muscle: "Triceps",
    muscleGroup: "chest_triceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${CDN}/0065.gif`,
    instructions: [
      "Cable set at face height, use rope or straight bar",
      "Elbows pinned to sides",
      "Push down to full extension",
      "Slowly return — elbows stay fixed",
    ],
    tips: "Keep elbows locked to sides. Only forearms move.",
    caloriesPerMin: 5,
  },
  {
    id: "face_pull",
    name: "Face Pulls",
    muscle: "Shoulders",
    muscleGroup: "shoulders",
    equipment: "cable",
    type: "gym",
    gifUrl: `${CDN}/0085.gif`,
    instructions: [
      "Set cable at face height with rope attachment",
      "Pull rope to face, elbows flared high",
      "Externally rotate wrists at the end",
      "Slowly return",
    ],
    tips: "Essential for shoulder health and posture. Don't skip this.",
    caloriesPerMin: 5,
  },
  {
    id: "cable_row",
    name: "Seated Cable Row",
    muscle: "Back",
    muscleGroup: "back_biceps",
    equipment: "cable",
    type: "gym",
    gifUrl: `${CDN}/0238.gif`,
    instructions: [
      "Sit at cable machine, feet on platform, slight knee bend",
      "Grip the handle with both hands",
      "Pull to your lower chest, squeezing shoulder blades",
      "Slowly extend back to full reach",
    ],
    tips: "Don't round your back at the stretch position.",
    caloriesPerMin: 6,
  },
  {
    id: "incline_db_press",
    name: "Incline DB Press",
    muscle: "Chest",
    muscleGroup: "chest_triceps",
    equipment: "dumbbell",
    type: "gym",
    gifUrl: `${CDN}/0177.gif`,
    instructions: [
      "Set bench to 30–45°",
      "Dumbbells at chest level, press upward",
      "Lower to feel the stretch",
      "Repeat",
    ],
    tips: "Targets upper chest. Don't go too steep — 30° is ideal.",
    caloriesPerMin: 6,
  },
  {
    id: "leg_curl",
    name: "Leg Curl Machine",
    muscle: "Hamstrings",
    muscleGroup: "glutes_hamstrings",
    equipment: "machine",
    type: "gym",
    gifUrl: `${CDN}/0057.gif`,
    instructions: [
      "Lie face down, pad just above heels",
      "Curl legs toward glutes",
      "Hold briefly at the top",
      "Lower slowly",
    ],
    tips: "Don't arch your lower back. Focus on the hamstring squeeze.",
    caloriesPerMin: 5,
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────
export function getExercisesByType(type: string): Exercise[] {
  return EXERCISE_LIBRARY.filter((e) => e.type === type);
}

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_LIBRARY.find((e) => e.id === id);
}

export const muscleEmoji: Record<string, string> = {
  chest: "💪", back: "🔙", shoulders: "🏋️", biceps: "💪",
  triceps: "💪", quads: "🦵", legs: "🦵", glutes: "🍑",
  hamstrings: "🦵", abs: "⚡", cardio: "❤️", "full body": "🔥",
};

// Muscle groups that can be trained daily (don't need rest)
export const DAILY_REPEAT_GROUPS = ["core", "cardio"];